# Generated by Django 5.1.6 on 2025-04-25 07:21

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_field_checkregex_alter_field_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutorPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.executor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('type', models.CharField(choices=[('ACT', 'Акт'), ('ORDER', 'Заказ'), ('REPORT', 'Отчёт')], max_length=10, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/servi/Desktop/Программистические шутки/ReportCreator/docs/templates'), verbose_name='Файл шаблона')),
                ('related_contractor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.contractorperson', verbose_name='Представитель (юридическое лицо) заказчика')),
                ('related_executor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.executorperson', verbose_name='Представитель (юридическое лицо) исполнителя')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.CharField(default='null__Null', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Русское название поля (для отображения)')),
                ('key_name', models.CharField(max_length=50, serialize=False, verbose_name='Английское название поля (по которому будет доступ в API)')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле?')),
                ('related_item', models.CharField(editable=False, max_length=30, verbose_name='К какому виду записи относится это поле (заполняется программно)')),
                ('type', models.CharField(choices=[('TEXT', 'Текстовое поле'), ('NUMBER', 'Числовое поле'), ('DATE', 'Дата и время'), ('CURRENCY', 'Денежная сумма'), ('BOOL', 'Логическое поле'), ('USER', 'ФИО другого участника')], max_length=10, verbose_name='Тип поля')),
                ('placeholder', models.CharField(max_length=50, null=True, verbose_name='Подсказка для заполнения поля')),
                ('validation_regex', models.CharField(max_length=200, null=True, verbose_name='Регулярное выражение для валидации')),
                ('secure_text', models.BooleanField(default=False, verbose_name='Это защищённое поле?')),
                ('error_text', models.TextField(null=True, verbose_name='Текст ошибки при валидации')),
                ('related_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.template', verbose_name='Связанный шаблон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('shown_date', models.DateField(verbose_name='Отображаемая дата')),
                ('save_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к сохранённому документу относительно C:\\Users\\servi\\Desktop\\Программистические шутки\\ReportCreator\\docs')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.template', verbose_name='Шаблон')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_values', to='backend.document')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_field', to='backend.documentfield')),
            ],
            options={
                'unique_together': {('document_id', 'field_id')},
            },
        ),
    ]
