# Generated by Django 5.1.6 on 2025-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_template_documentfield_document_documentsvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='key_name',
            field=models.CharField(max_length=50, verbose_name='Английское название поля (по которому будет доступ в API)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='englName',
            field=models.CharField(max_length=50, verbose_name='Английское название поля (по которому будет доступ в API)'),
        ),
    ]
