# Generated by Django 5.1.6 on 2025-04-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_field_id_alter_field_englname_usersvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='englName',
            new_name='key_name',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='relatedItem',
            new_name='related_item',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='checkRegex',
            new_name='validation_regex',
        ),
        migrations.RenameField(
            model_name='usersvalues',
            old_name='field',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='usersvalues',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='usersvalues',
            unique_together={('user_id', 'field_id')},
        ),
    ]
