# Generated by Django 5.1.6 on 2025-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_englname_field_key_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='field',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Обязательное поле?'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текстовое поле'), ('PASSWORD', 'Пароль'), ('NUMBER', 'Числовое поле'), ('DATE', 'Дата и время'), ('CURRENCY', 'Денежная сумма'), ('BOOL', 'Логическое поле'), ('USER', 'ФИО другого участника')], max_length=10, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
