# Generated by Django 5.1.6 on 2025-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersvalues',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
