# Generated by Django 5.1.6 on 2025-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_contractor_related_executor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentfield',
            unique_together={('key_name', 'related_item')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('key_name', 'related_item')},
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='related_info',
            field=models.JSONField(editable=False, null=True, verbose_name='Дополнительная информация для этого поля при related_item = COMBOBOX'),
        ),
        migrations.AlterField(
            model_name='field',
            name='related_info',
            field=models.JSONField(editable=False, null=True, verbose_name='Дополнительная информация для этого поля при related_item = COMBOBOX'),
        ),
    ]
