# Generated by Django 5.1.6 on 2025-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_documentfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentfield',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentfield',
            constraint=models.UniqueConstraint(fields=('key_name', 'related_item'), name='document_field_key_name_related_item_combination'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('key_name', 'related_item'), name='field_key_name_related_item_combination'),
        ),
    ]
