# Generated by Django 5.1.6 on 2025-04-26 07:24

from django.db import migrations, models
from backend.scripts.initial_fields import *


def create_initial_items(apps, schema_editor):
    Field = apps.get_model('backend', 'Field')

    for dic in ALL_ITEMS:
        for field in dic:
            # Так как могут быть добавлены новые поля, `get_or_create` не подходит. 
            # Вмето этого нужно овершать проверку по ключевым полям и создавать поля только если они есть.
            if not Field.objects.filter(key_name=field['key_name'], related_item=field['related_item']).exists():
                Field.objects.create(
                    id=f"{field['key_name']}__{field['related_item']}",
                    is_custom=False,
                    **field)

def revert(apps, schema_editor):
    Field = apps.get_model('backend', 'Field')
    db_alias = schema_editor.connection.alias
    for dic in [USER, EXECUTOR, CONTRACTOR, TEMPLATE, EXECUTOR_PERSON, CONTRACTOR_PERSON]:
        for field in dic:
            Field.objects.using(db_alias).filter(key_name=field['key_name'], related_item=field['related_item']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_documentfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='is_custom',
            field=models.BooleanField(default=False, editable=False, verbose_name='Это поле создано пользователем?'),
        ),
        migrations.AddField(
            model_name='field',
            name='is_custom',
            field=models.BooleanField(default=False, editable=False, verbose_name='Это поле создано пользователем?'),
        ),
        migrations.RunPython(create_initial_items, revert)
    ]
