# Generated by Django 5.1.6 on 2025-04-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_initial_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
