# Generated by Django 5.1.6 on 2025-05-24 05:41

from core.settings.base import TEMPLATES_FOLDER
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_documentfield_is_custom_field_is_custom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='template_name',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='type',
            new_name='template_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='file',
        ),
        migrations.AddField(
            model_name='template',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to=TEMPLATES_FOLDER, verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='document',
            name='save_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=f'Путь к сохранённому документу относительно {TEMPLATES_FOLDER}'),
        ),
    ]
