# Generated by Django 5.1.6 on 2025-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_rename_name_template_template_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='save_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к сохранённому документу относительно \\backend\\media\\docs'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='Файл шаблона'),
        ),
    ]
