# Generated by Django 5.1.6 on 2025-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_document_save_path_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contractorperson',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'surname'), name='FIO_contractor_combination'),
        ),
        migrations.AddConstraint(
            model_name='executorperson',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'surname'), name='FIO_executor_combination'),
        ),
    ]
