# Generated by Django 5.1.6 on 2025-05-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_contractorperson_fio_contractor_combination_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contractor',
            constraint=models.UniqueConstraint(fields=('company_name', 'company_fullName'), name='company_names_combination'),
        ),
    ]
