# Generated by Django 5.1.6 on 2025-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_contractor_contract_date_contractor_contract_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('related_contractor_person', 'related_executor_person', 'template_name'), name='persons_name_combination'),
        ),
    ]
