# Generated by Django 5.1.6 on 2025-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_documentfield_name_alter_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractor',
            name='company_names_combination',
        ),
        migrations.RemoveConstraint(
            model_name='contractorperson',
            name='FIO_contractor_combination',
        ),
        migrations.RemoveConstraint(
            model_name='documentfield',
            name='document_field_key_name_related_item_combination',
        ),
        migrations.RemoveConstraint(
            model_name='executorperson',
            name='FIO_executor_combination',
        ),
        migrations.RemoveConstraint(
            model_name='tablefield',
            name='table_field_key_name_related_item_combination',
        ),
        migrations.AddField(
            model_name='tablefield',
            name='is_summable',
            field=models.BooleanField(default=False, verbose_name='Суммируемый столбец'),
        ),
        migrations.AddConstraint(
            model_name='contractor',
            constraint=models.UniqueConstraint(fields=('company_name', 'company_fullName', 'related_executor'), name='company_names_combination'),
        ),
        migrations.AddConstraint(
            model_name='contractorperson',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'surname', 'company'), name='FIO_contractor_combination'),
        ),
        migrations.AddConstraint(
            model_name='documentfield',
            constraint=models.UniqueConstraint(fields=('key_name', 'related_item', 'related_template'), name='document_field_key_name_related_item_combination'),
        ),
        migrations.AddConstraint(
            model_name='executorperson',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'surname', 'company'), name='FIO_executor_combination'),
        ),
        migrations.AddConstraint(
            model_name='tablefield',
            constraint=models.UniqueConstraint(fields=('key_name', 'related_item', 'related_template'), name='table_field_key_name_related_item_combination'),
        ),
    ]
