# Generated by Django 5.1.6 on 2025-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_contractor_company_names_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefield',
            name='is_autoincremental',
            field=models.BooleanField(default=False, verbose_name='Автосуммируемый столбец'),
        ),
    ]
