# Generated by Django 5.1.6 on 2025-06-01 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_tablefield_is_autoincremental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contractor_city',
        ),
        migrations.AddField(
            model_name='contractorperson',
            name='contract_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorperson',
            name='contract_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorperson',
            name='contractor_city',
            field=models.CharField(default='Москва', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorperson',
            name='person_type',
            field=models.CharField(default="ООО 'Компания'", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executorperson',
            name='person_type',
            field=models.CharField(default="ООО 'Компания'", max_length=64),
            preserve_default=False,
        ),
    ]
