# Generated by Django 5.1.6 on 2025-06-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_contractor_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorperson',
            name='person_type',
            field=models.TextField(default="OAO 'Название компании'", max_length=128),
        ),
        migrations.AlterField(
            model_name='executorperson',
            name='person_type',
            field=models.TextField(default="OAO 'Название компании'", max_length=128),
        ),
    ]
