# Generated by Django 5.1.6 on 2025-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_contractorperson_person_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersvalues',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usersvalues',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
