# Generated by Django 5.1.6 on 2025-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_usersvalues_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.IntegerField(default=0, verbose_name='Номер документа в шаблоне'),
        ),
    ]
