# Generated by Django 5.1.6 on 2025-04-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_user_patronymic_field_is_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='englName',
            new_name='key_name',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='relatedItem',
            new_name='related_item',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='checkRegex',
            new_name='validation_regex',
        ),
        migrations.RenameField(
            model_name='usersvalues',
            old_name='field',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='usersvalues',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='usersvalues',
            unique_together={('user_id', 'field_id')},
        ),
        migrations.CreateModel(
            name='ContractorPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutorPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.executor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
