# Generated by Django 5.1.6 on 2025-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_user_patronymic_field_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='secure_text',
            field=models.BooleanField(default=False, verbose_name='Это защищённое поле?'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текстовое поле'), ('NUMBER', 'Числовое поле'), ('DATE', 'Дата и время'), ('CURRENCY', 'Денежная сумма'), ('BOOL', 'Логическое поле'), ('USER', 'ФИО другого участника')], max_length=10, verbose_name='Тип поля'),
        ),
    ]
