# Generated by Django 5.1.6 on 2025-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', 'initial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='error_text',
            field=models.TextField(null=True, verbose_name='Текст ошибки при валидации'),
        ),
    ]
