# Generated by Django 5.1.6 on 2025-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', 'set_error_text_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
