# Generated by Django 5.1.6 on 2025-04-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_usersvalues_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='related_executor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_executor', to='backend.executor'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='related_info',
            field=models.JSONField(editable=False, null=True, verbose_name='Дополнительная информация для этого поля при type = COMBOBOX'),
        ),
        migrations.AddField(
            model_name='field',
            name='related_info',
            field=models.JSONField(editable=False, null=True, verbose_name='Дополнительная информация для этого поля при type = COMBOBOX'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текстовое поле'), ('NUMBER', 'Числовое поле'), ('DATE', 'Дата и время'), ('CURRENCY', 'Денежная сумма'), ('BOOL', 'Логическое поле'), ('USER', 'ФИО другого участника'), ('COMBOBOX', 'Выпадающий список из других записей')], max_length=10, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текстовое поле'), ('NUMBER', 'Числовое поле'), ('DATE', 'Дата и время'), ('CURRENCY', 'Денежная сумма'), ('BOOL', 'Логическое поле'), ('USER', 'ФИО другого участника'), ('COMBOBOX', 'Выпадающий список из других записей')], max_length=10, verbose_name='Тип поля'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfield',
            unique_together={('key_name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('key_name', 'type')},
        ),
    ]
