# Generated by Django 5.1.6 on 2025-04-05 11:41

from django.db import migrations


def create_initial_user_fields(apps, schema_editor):
    Field = apps.get_model('backend', 'Field')

    initial_fields = [
        {
            'name': 'Фамилия',
            'key_name': 'last_name',
            'is_required': True,
            'placeholder': 'Ваша фамилия',
            'type': 'TEXT',
            'validation_regex': '^[а-яА-Я]+(-[а-яА-Я]+)*$',
            'related_item': "User"
        },
        {
            'name': 'Имя',
            'key_name': 'first_name',
            'is_required': True,
            'placeholder': 'Ваше имя',
            'type': 'TEXT',
            'validation_regex': '^[а-яА-Я]+(-[а-яА-Я]+)*$',
            'related_item': "User"
        },
        {
            'name': 'Отчество',
            'key_name': 'patronymic',
            'is_required': False,
            'placeholder': 'Ваше отчество',
            'type': 'TEXT',
            'validation_regex': '^[а-яА-Я]*$',
            'related_item': "User"
        }
    ]

    for field in initial_fields:
        Field.objects.get_or_create(**field)

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_field_checkregex_alter_field_placeholder'),
    ]

    operations = [
        migrations.RunPython(create_initial_user_fields),
    ]
