# Migration 0009 - Создание первичных полей пользователя
# Generated by Django 5.1.6 on 2025-04-05 11:41

from django.db import migrations


def create_initial_user_fields(apps, schema_editor):
    Field = apps.get_model('backend', 'Field')

    initial_fields = [
        {
            'name': 'Логин',
            'key_name': 'username',
            'is_required': True,
            'placeholder': 'Ваш логин пользователя',
            'type': 'TEXT',
            'validation_regex': '^[a-zA-Z0-9_-]{4,16}$',
            'related_item': "User",
            'secure_text': False,
        },
        {
            'name': 'Пароль',
            'key_name': 'password',
            'is_required': True,
            'placeholder': 'Ваш пароль',
            'type': 'TEXT',
            # минимум 8 символов, минимум одна цифра
            'validation_regex': '^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$',
            'related_item': "User",
            'secure_text': True,
        },
        {
            'name': 'Фамилия',
            'key_name': 'last_name',
            'is_required': True,
            'placeholder': 'Ваша фамилия',
            'type': 'TEXT',
            'validation_regex': '^[а-яА-Я]+(-[а-яА-Я]+)*$',
            'related_item': "User",
            'secure_text': False,
        },
        {
            'name': 'Имя',
            'key_name': 'first_name',
            'is_required': True,
            'placeholder': 'Ваше имя',
            'type': 'TEXT',
            'validation_regex': '^[а-яА-Я]+(-[а-яА-Я]+)*$',
            'related_item': "User",
            'secure_text': False,
        },
        {
            'name': 'Отчество',
            'key_name': 'patronymic',
            'is_required': False,
            'placeholder': 'Ваше отчество',
            'type': 'TEXT',
            'validation_regex': '^[а-яА-Я]*$',
            'related_item': "User",
            'secure_text': False,
        }
    ]

    for field in initial_fields:
        Field.objects.get_or_create(**field)
    
    if "error_text" in Field._meta.get_fields():
        from .set_error_text_values import set_error_text_values

class Migration(migrations.Migration):

    # ЗДЕСЬ ОН МИГРАЦИЯ 0009
    dependencies = [
        ('backend', '0008_field_secure_text_alter_field_type'),
    ]

    operations = [
        migrations.RunPython(create_initial_user_fields),
    ]
